services:
  - type: web
    name: eda-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://tech_user:Nextyou%4024@cluster0.ush6z3w.mongodb.net/?retryWrites=true&w=majority
      - key: PORT
        value: 5001
